-- MySQL Script generated by MySQL Workbench
-- dom 16 ago 2020 01:09:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `titulo_empolgante` JSON NULL,
  `descricao_empolgante` JSON NULL,
  `descricao` JSON NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`noticias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_publicacao` DATE NULL,
  `conteudo` JSON NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`noticias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_publicacao` DATE NULL,
  `conteudo` JSON NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`midias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`midias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_jogo` INT NULL,
  `id_noticia` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `link` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_midias_1_idx` (`id_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_midias_jogo`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `mydb`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_midias_noticia`
    FOREIGN KEY ()
    REFERENCES `mydb`.`noticias` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
