-- MySQL Script generated by MySQL Workbench
-- sáb 22 ago 2020 15:16:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `data_lancamento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Midias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Midias` (
  `id` INT NOT NULL,
  `jogo_id` INT NOT NULL,
  `noticia_id` INT NOT NULL,
  `link` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `misc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Midias_Jogos_idx` (`jogo_id` ASC) VISIBLE,
  INDEX `fk_Midias_Noticias1_idx` (`noticia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_Jogos`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `mydb`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_Noticias1`
    FOREIGN KEY (`noticia_id`)
    REFERENCES `mydb`.`Noticias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plataformas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plataformas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlataformasDisponiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlataformasDisponiveis` (
  `jogo_id` INT NOT NULL,
  `plataforma_id` INT NOT NULL,
  PRIMARY KEY (`jogo_id`, `plataforma_id`),
  INDEX `fk_Plataformas_has_Jogos_Jogos1_idx` (`jogo_id` ASC) VISIBLE,
  INDEX `fk_Plataformas_has_Jogos_Plataformas1_idx` (`plataforma_id` ASC) VISIBLE,
  CONSTRAINT `fk_Plataformas_has_Jogos_Plataformas1`
    FOREIGN KEY (`plataforma_id`)
    REFERENCES `mydb`.`Plataformas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plataformas_has_Jogos_Jogos1`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `mydb`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Textos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Textos` (
  `id` INT NOT NULL,
  `jogo_id` INT NOT NULL,
  `noticia_id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `lang` VARCHAR(7) NULL,
  `texto` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Midias_Jogos_idx` (`jogo_id` ASC) VISIBLE,
  INDEX `fk_Midias_Noticias1_idx` (`noticia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Midias_Jogos0`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `mydb`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Midias_Noticias10`
    FOREIGN KEY (`noticia_id`)
    REFERENCES `mydb`.`Noticias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL DEFAULT 'grey',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TagsDaNoticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TagsDaNoticia` (
  `noticia_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`noticia_id`, `tag_id`),
  INDEX `fk_Noticias_has_Tags_Tags1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_Noticias_has_Tags_Noticias1_idx` (`noticia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Noticias_has_Tags_Noticias1`
    FOREIGN KEY (`noticia_id`)
    REFERENCES `mydb`.`Noticias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_has_Tags_Tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TagsDoJogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TagsDoJogo` (
  `jogo_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`jogo_id`, `tag_id`),
  INDEX `fk_Jogos_has_Tags_Tags1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_Jogos_has_Tags_Jogos1_idx` (`jogo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Jogos_has_Tags_Jogos1`
    FOREIGN KEY (`jogo_id`)
    REFERENCES `mydb`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_has_Tags_Tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
